### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by codingjeremy** [android/fit#10]
<a href="https://github.com/jaag12"><img src="https://avatars3.githubusercontent.com/u/32569818?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaag12](https://github.com/jaag12)**
_Thursday Nov 16, 2017 at 09:09 GMT_
_Originally opened as https://github.com/googlesamples/android-fit/issues/28_

----

Error when trying new versions of Google Fit samples,

` E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
                                                                                                      Process: com.google.android.gms.fit.samples.basicrecordingapi, PID: 22949
                                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.google.android.gms.auth.api.signin.GoogleSignInAccount.getAccount()' on a null object reference
                                                                                                          at com.google.android.gms.common.api.GoogleApi.zzagd(Unknown Source)
                                                                                                          at com.google.android.gms.common.api.GoogleApi.zza(Unknown Source)
                                                                                                          at com.google.android.gms.common.api.internal.zzbr.<init>(Unknown Source)
                                                                                                          at com.google.android.gms.common.api.internal.zzbp.zzb(Unknown Source)
                                                                                                          at com.google.android.gms.common.api.internal.zzbp.handleMessage(Unknown Source)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)`

 have changed the methods and I have noticed that since then my application using the old methods does not record data for DataType TYPE_ACTIVITY_SEGMENT, TYPE_STEP_COUNT_DELTA and sometimes TYPE_HEART_RATE_BPM. What is the solution?

**Comment by codingjeremy** [comment]
<a href="https://github.com/yoshimaa"><img src="https://avatars1.githubusercontent.com/u/10446783?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoshimaa](https://github.com/yoshimaa)**
_Tuesday Nov 28, 2017 at 12:48 GMT_

----

@jaag12 
hi, which sample did you try?

**Comment by codingjeremy** [comment]
<a href="https://github.com/StephenMPapadatos"><img src="https://avatars1.githubusercontent.com/u/18648292?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [StephenMPapadatos](https://github.com/StephenMPapadatos)**
_Thursday Nov 30, 2017 at 15:32 GMT_

----

stepCounter and HistoryApiSample both have this error

**Comment by codingjeremy** [comment]
<a href="https://github.com/swapps"><img src="https://avatars2.githubusercontent.com/u/8030831?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [swapps](https://github.com/swapps)**
_Monday Dec 04, 2017 at 09:12 GMT_

----

Hi, any update about this error ? it's really annoying

**Comment by codingjeremy** [comment]
<a href="https://github.com/yoshimaa"><img src="https://avatars1.githubusercontent.com/u/10446783?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoshimaa](https://github.com/yoshimaa)**
_Monday Dec 04, 2017 at 14:08 GMT_

----

@swapps 
ok, ill make for you, so which one do you wanna?

**Comment by codingjeremy** [comment]
<a href="https://github.com/ankit209"><img src="https://avatars0.githubusercontent.com/u/11189984?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ankit209](https://github.com/ankit209)**
_Thursday Dec 07, 2017 at 11:39 GMT_

----

I am getting the same issue with play-services 11.6.0 and the latest session api samples at http://bit.ly/2AFpN8D

**Comment by codingjeremy** [comment]
<a href="https://github.com/david99999"><img src="https://avatars2.githubusercontent.com/u/4248801?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [david99999](https://github.com/david99999)**
_Thursday Dec 07, 2017 at 14:20 GMT_

----

Hi everyone, I was getting this error too, it seems that we need to configure the demo project to work with our debug-release keystores, so all we need to do is [Get an OAuth 2.0 Client ID](https://developers.google.com/fit/android/get-api-key) and run the application again, no changes in code needed, only registering our SHA1 fingerprint.

**Comment by codingjeremy** [comment]
<a href="https://github.com/nikhil-tambe"><img src="https://avatars0.githubusercontent.com/u/25247161?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhil-tambe](https://github.com/nikhil-tambe)**
_Wednesday Jan 03, 2018 at 11:33 GMT_

----

@jaag12
make the following changes to your gradle.properties, sync and run the app
```
google_play_services_library=11.8.0
google_support_library=26.1.0
```
this solved the crash issue I faced with the same log printed in your logcat.

**Comment by codingjeremy** [comment]
<a href="https://github.com/lifeLessCoder"><img src="https://avatars1.githubusercontent.com/u/33070301?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lifeLessCoder](https://github.com/lifeLessCoder)**
_Friday Jun 22, 2018 at 15:16 GMT_

----

Hey guys need a little help here. I'm not able to remove the listener in the sensorsApi sample. The log cat says "Listener was not removed" . Don't know what to do. Stuck on this problem for a long time now.

**Comment by codingjeremy** [comment]
<a href="https://github.com/roufalnewage"><img src="https://avatars2.githubusercontent.com/u/51320050?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [roufalnewage](https://github.com/roufalnewage)**
_Tuesday Jun 18, 2019 at 06:58 GMT_

----

check your application id and package name are same. that was my issue now working perfectly
